---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## ratelimitr
Use ratelimitr to limit the rate at which functions are called. A rate-limited function that allows `n` calls per `period` will never have a window of time of length `period` that includes more than `n` calls. 

```{r ex1}
library(ratelimitr)
f <- function() NULL

# create a version of f that can only be called 10 times per second
f_lim <- limit_rate(f, rate(n = 10, period = 1))

# time without limiting
system.time(replicate(11, f()))

# time with limiting
system.time(replicate(11, f_lim()))
```

You can add multiple rates
```{r ex2}
f_lim <- limit_rate(
    f, 
    rate(n = 10, period = .01), 
    rate(n = 50, period = .1)
)

# reset function is for convenience. it does not modify the original 
# rate-limited function, just returns a new one
timef <- function(n) {
    replicate(n, f_lim())
    reset(f_lim)
}

library(microbenchmark)
microbenchmark(
    do10 = f_lim <- timef(10),
    do11 = f_lim <- timef(11),
    do50 = f_lim <- timef(50),
    do51 = f_lim <- timef(51),
    times = 20L
)
```

## To install:

```{r install, eval = FALSE}
devtools::install_github("tarakc02/ratelimitr")
```

## Requirements
* R
* [Rcpp](https://cran.r-project.org/web/packages/Rcpp/index.html)
